services:
  app:
    build:
      context: .
    ports:
      - 8081:8081
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - my-network

  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    ports:
      - 5433:5432
    networks:
      - my-network
    volumes:
      - postgres-data:/var/lib/postgresql/data              # for data persistence - docker compose down -v --- to down volume and network and container
#      - ./src/main/resources/schema-postgres.sql:/docker-entrypoint-initdb.d/init.sql    # for schema creation

networks:
  my-network:
    driver: bridge

volumes:
  postgres-data: