spring.application.name=auth-service
# ===============================
# Server
# ===============================
server.port=8081

# ===============================
# Database (PostgreSQL)
# ===============================

## uncomment for docker-compose inside container and only if not added as env variable in docker-compose file
#spring.datasource.url=jdbc:postgresql://postgres:5432/postgres
#spring.datasource.username=root
#spring.datasource.password=root

## comment below property if running through docker-compose
#spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
#spring.datasource.username=postgres
#spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

## uncomment for docker-compose inside container
spring.sql.init.mode=always
spring.sql.init.platform=postgres

#uncomment only when you want .sql file should run after your hibernate but in thi case of schema schema-postgres.sql must run \
#  before hibernate, so hibernate can create table under this schema (Since we have form custom schema not work in default publc schema
#spring.jpa.defer-datasource-initialization=true

#jpa.properties.hibernate.cache.use_second_level_cache=false
#jpa.properties.hibernate.cache.use_query_cache=false
#jpa.properties.hibernate.cache.region.factory_class=org.redisson.hibernate.cache.RedissonRegionFactory
#jpa.properties.hibernate.generate_statistics=false
#jpa.properties.hibernate.cache.redisson.config=classpath:redisson.yaml

# ===============================
# Redis Configuration
# ===============================
#spring.redis.host=localhost
#spring.redis.port=6379



# ===============================
# JWT Configuration
# ===============================
security.jwt.secret=MySuperSecretKeyForJwtTokenGeneration123456
security.jwt.expiration-ms=3600000
# 1 hour

# ===============================
# Spring Security
# ===============================
spring.security.user.name=disabled
spring.security.user.password=disabled

# ===============================
# Logging
# ===============================
logging.level.root=INFO
logging.level.com.arth.auth=DEBUG